name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml
  lint:
    uses: ./.github/workflows/lint.yaml
  format:
    uses: ./.github/workflows/format.yaml
