name: format

on: [workflow_call]

jobs:
  format:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install project
        run: pip install .[formatting]
      - name: Run codespell
        run: codespell --enable-colors
      - name: Run ruff
        run: ruff format --diff .