name: Tests 

on: [workflow_call]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11" ]
        os: [  ubuntu-latest, macos-latest, windows-latest, ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install project
        run: python -m pip install .[testsuite]
      - name: Run unit tests on Python ${{ matrix.python-version }} on ${{ matrix.os }}
        run: pytest
